background image, opacity, nav align, general spacing
81jumpstr/Setup01 pull request #12
Opened 2016-11-04 13:12 UTC by 81jumpstr

## Scope

Between this pr and the previous, feat/footer, lost track of what I did where...
Not cool! ...I know... I'll make sure it won't happen again.

2016-11-04 13:24 UTC, royscheeren requested changes

2016-11-04 13:24 UTC, royscheeren commented on style.css
>     width: 37rem !important;
no importants, no fixed widths ;)

2016-11-04 13:27 UTC, 81jumpstr commented on style.css
>     width: 37rem !important;
Ha! got me. these tricks don't work on you, hey. Not to trick you, though. Ok...cool, I'll fix that right away

2016-11-07 07:10 UTC, royscheeren requested changes

2016-11-07 07:10 UTC, royscheeren commented on style.css
>     font-size: 2rem !important;
!important

2016-11-07 07:10 UTC, royscheeren commented on style.css
>     color: #1E90FF !important;
!important

2016-11-07 07:10 UTC, royscheeren commented on style.css
>     font-family: 'Over the Rainbow' !important;
!important

2016-11-07 07:10 UTC, royscheeren commented on style.css
> +   height: 0 auto;
Height of 0 auto does not do anything. I'm pretty sure if you delete this line it will be exactly the same

2016-11-07 08:17 UTC, 81jumpstr commented
I'm getting the feeling that, in actual fact, I should preferably just never use !important...? :o,

2016-11-07 11:15 UTC, royscheeren requested changes

2016-11-07 11:15 UTC, royscheeren commented on index.php
> +	  </ul>
You dont want to wrap a div around an li. 
It should **always** be `ul > li`.
You are welcome to do `ul > li > div` but never `ul > div > li`.
In this case even `<li class='single-post'>` would be best

2016-11-07 11:15 UTC, royscheeren commented on style.css
>    content: 'Show less';
See comment on earlier PR

2016-11-07 12:14 UTC, 81jumpstr commented on index.php
> +	  </ul>
Alright!

2016-11-07 14:07 UTC, royscheeren commented
Looking good dude, now  theres just that commented out piece in the functions.php that doesn't really make sense.

2016-11-14 08:43 UTC, royscheeren requested changes

2016-11-14 08:43 UTC, royscheeren commented on functions.php
> +  set_post_thumbnail_size( 100, 50, true );
Don't add functions straight into functions.php. You want to have control over when these functions will be executed: 

``` 
add_action('init', 'setupshop_theme_init');
function setupshop_theme_init() {
  add_theme_support( 'post-thumbnails' ); 
  set_post_thumbnail_size( 100, 50, true );
}

2016-11-14 08:43 UTC, royscheeren commented on single.php
> +		    <div>
Alignment is off

2016-11-15 09:46 UTC, royscheeren requested changes

2016-11-15 09:46 UTC, royscheeren commented on footer.php
> +  			</li>
Small alignment issue here. the `</li>` should be a tab back

2016-11-15 09:46 UTC, royscheeren commented on index.php
> +	}
This goes into your functions.php. Never put functions like these in your template files.

2016-11-15 09:46 UTC, royscheeren commented on single.php
> +			<div class="pull-right">
What's the `pull-right` class for?

2016-11-15 10:00 UTC, 81jumpstr commented on single.php
> +			<div class="pull-right">
I wanted to try out how the layout would look if I had the posts images on the right instead of left as they currently are. I'm also learning about thumbnails...alternatively, can I just style the images to same size for now?

2016-11-15 10:06 UTC, 81jumpstr commented on footer.php
> +  			</li>
This is odd, on sublime everything is properly aligned, on github the alignment shifts and I don't know what github expects me to do. Could github have a bug of sort? It looks perfectly fine on sublime

2016-11-15 11:06 UTC, royscheeren approved these changes

2016-11-16 12:12 UTC, merged