fixed indentation, removed thumbnail size setting
81jumpstr/Setup01 pull request #13
Opened 2016-11-16 13:12 UTC by 81jumpstr

To all reviewing this repo for the first time, "feat/branches" are a bit of a mess. From here on, I'll be naming them "fix/branches"...getting back to standard practice...

2016-11-16 14:09 UTC, royscheeren commented
What is the mess?

2016-11-16 14:13 UTC, royscheeren requested changes

2016-11-16 14:13 UTC, royscheeren commented on functions.php
>    add_action('wp_enqueue_scripts', 'Setupshop_script_enqueue');
Don't use capital letters in function names. Thats for classes.

2016-11-16 14:13 UTC, royscheeren commented on functions.php
>    add_action( 'widgets_init', 'arphabet_widgets_init' );
Consider your function names. Think about what it is you're copy pasting. The `arphabet` is nothing more than a prefix. You shouldn't just take that with. Just make sure the second part of the add_action is the function you're calling.

2016-11-16 14:13 UTC, royscheeren commented on functions.php
> +  add_action( 'init', 'register_my_menu' );
There should be no indentation here.

2016-11-17 08:54 UTC, 81jumpstr commented on functions.php
>    add_action('wp_enqueue_scripts', 'Setupshop_script_enqueue');
Ok, no caps...the mess was the way I wasn't branching properly.

2016-11-17 11:57 UTC, merged