fixed indentation
81jumpstr/Setup01 pull request #34
Opened 2016-11-28 08:47 UTC by 81jumpstr

2016-11-28 12:17 UTC, royscheeren requested changes

2016-11-28 12:17 UTC, royscheeren commented on footer.php
> +			  <li class="footer-icons">
Indentation seems bigger from the ul to the li than from the li to the a. Seems like you have a double indent before the li

2016-11-28 12:46 UTC, 81jumpstr commented
Problem
- Corrections, missed something. 
   7ce47d1

Solution
- Fixed
   faf26ba

2016-11-29 07:50 UTC, royscheeren approved these changes

2016-11-29 07:58 UTC, merged