Fix/single content li
81jumpstr/Setup01 pull request #35
Opened 2016-11-28 10:16 UTC by 81jumpstr

2016-11-28 12:21 UTC, royscheeren requested changes

2016-11-28 12:21 UTC, royscheeren commented on single.php
> +            <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
You don't need to give each article an ID. Just a class is more than fine.

2016-11-28 12:21 UTC, royscheeren commented on single.php
> +              </div>
Indentation between the opening and closing of this div is off

2016-11-28 12:21 UTC, royscheeren commented on single.php
> +      <li>
You only open your `li` at `the_content` all the rest is floating inside your `ul`. That won't work. A `ul` can only consist of `li`s as child elements. Read through this file, structurally it doesn't make sense.

2016-11-28 13:22 UTC, 81jumpstr commented
Problem
- li's not making sense

Solution
- Corrections; commit 2449984

2016-11-28 13:31 UTC, 81jumpstr commented
Problem
- Missed something on the previous commit.

Solution
- This commit has all the requested changes 	74639a7

2016-11-30 08:19 UTC, royscheeren approved these changes

2016-11-30 08:32 UTC, merged