Fix/page dotphp indentation
81jumpstr/Setup01 pull request #41
Opened 2016-12-01 14:56 UTC by 81jumpstr

...and fixed ul as well, based on knowledge gained while fixing index.php.

2016-12-02 07:38 UTC, royscheeren requested changes

2016-12-02 07:38 UTC, royscheeren commented on page.php
> +        <ul class="posts">
It's a page, so you'll only have one post, not a list of posts. This means your ul is unnecessary.

2016-12-02 08:09 UTC, 81jumpstr commented
Done!

2016-12-02 08:52 UTC, royscheeren commented
The li is not the only part of a html list remember.

2016-12-07 14:59 UTC, royscheeren approved these changes

2016-12-07 15:01 UTC, merged