fixed ul, li, indentation
81jumpstr/Setup01 pull request #42
Opened 2016-12-02 08:30 UTC by 81jumpstr

2016-12-02 08:53 UTC, royscheeren requested changes

2016-12-02 08:53 UTC, royscheeren commented on page-upskill.php
> +          <li>
li in wrong place

2016-12-02 09:57 UTC, 81jumpstr commented
Thinking about it for too long. My best says; This seems to make more sense to me.

2016-12-02 10:17 UTC, royscheeren commented
Sorry dude but no. I might not be explaining it correctly, it doesn't seem to stick.

2016-12-02 10:47 UTC, 81jumpstr commented
Attempt #3

2016-12-02 12:57 UTC, 81jumpstr commented
Page-upskill-markup, placing ul…steps :

-	Prepare to put main content in a div or container
-	Check whether posts are available
-	Be ready to post when found
-	Retrieve and be ready to post relevant content and page
-	Retrieve be ready to post the available article
-	Retrieve and be ready to include the post title
-	Check whether thumbnails available
-	Be ready to post thumbnails in assigned div
-	Stop checking for thumbnails
-	Retrieve and be ready to print out the post category
-	Create or open an unordered list
-	Post all retrieved content queueing to be posted
-	Once all above steps have been executed, stop looping to find available posts
-	Then quit checking whether posts are available
-	Close the main content container

2016-12-06 07:41 UTC, royscheeren reviewed
Besides indentation the formatting is looking good. But, if I look at the file name I see it's a page. There will be only one post ever in the loop.

2016-12-06 07:52 UTC, 81jumpstr commented
I woke up this morning remembering that you did mention at some point that I don't need to create a list. Just couldn't remember in regard to what. I was about to trace back our conversations...so my brain is working...ok, cool

2016-12-06 09:41 UTC, 81jumpstr commented
I know we said we don't need a list for page template files. 
I just want to see if I fully understand, should I come across a similar task in the future.

2016-12-06 10:03 UTC, royscheeren requested changes

2016-12-06 10:03 UTC, royscheeren commented on page-upskill.php
> +            <?php the_title('<h1 class="entry-title">','</h1>' ); ?>
Your title is a part of the article, so it should go in there

2016-12-06 10:03 UTC, royscheeren commented on page-upskill.php
> +            <?php get_template_part( 'content', 'page' ); ?>
What's in your template part?

2016-12-06 10:03 UTC, royscheeren commented on page-upskill.php
> +        </ul>
You only need a list if you display multiple posts, which the main loop on a page won't have.

There's two parts to this whole story:
- Formatting your html and php correctly
- Knowing when to use which elements

2016-12-06 11:53 UTC, 81jumpstr commented on page-upskill.php
> +            <?php the_title('<h1 class="entry-title">','</h1>' ); ?>
So, this part is good?

2016-12-06 11:55 UTC, 81jumpstr commented on page-upskill.php
> +            <?php get_template_part( 'content', 'page' ); ?>
Should I just remove it? Another 1 of those "in the future perhaps" things.

2016-12-06 11:55 UTC, 81jumpstr commented on page-upskill.php
> +        </ul>
Will remove ul and li's

2016-12-06 12:21 UTC, royscheeren requested changes

2016-12-06 12:21 UTC, royscheeren commented on page-upskill.php
>              <?php the_title('<h1 class="entry-title">','</h1>' ); ?>
Your title is still not part of your article.

2016-12-06 12:23 UTC, 81jumpstr commented on page-upskill.php
>              <?php the_title('<h1 class="entry-title">','</h1>' ); ?>
You meant inside the article tag?

2016-12-07 14:59 UTC, closed without merging